services:
    java-labs:
        build: .
        container_name: jakarta-ee-docker-labs

        environment:
            HTTP_PORT: "8080"
            DB_PORT: "5432"
            DB_NAME: labdb
            DB_USER: labuser
            DB_PASS: labpass

        ports:
            - "8080:8080" # приложение GlassFish
            - "4848:4848" # GlassFish Admin
            - "5432:5432" # PostgreSQL
            - "8443:8443" # VS Code / code-server

        volumes:
            - ./:/work
            - pgdata:/var/lib/postgresql/data

        restart: unless-stopped

volumes:
    pgdata:
