<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>edu.demo</groupId>
        <artifactId>lab-demo</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>server</artifactId>
    <packaging>war</packaging>

    <dependencies>
        <!-- Jakarta EE 11 API (GlassFish 8 уже содержит реализации, поэтому provided) -->
        <dependency>
            <groupId>jakarta.platform</groupId>
            <artifactId>jakarta.jakartaee-api</artifactId>
            <version>11.0.0</version>
            <scope>provided</scope>
        </dependency>

        <!-- JDBC driver -->
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>42.7.4</version>
        </dependency>
    </dependencies>

    <build>
        <finalName>lab-demo</finalName>
    </build>
</project>